=== DLab/FONDEF-PID/GeneradorRAD/Entity.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Entity" xmlns:tns="http://www.example.org/Entity" elementFormDefault="qualified">

	<element name="Entity" type="tns:EntityType"></element>


	<complexType name="EntityType">
		<sequence>
			<element name="field" type="tns:FieldType"
				maxOccurs="unbounded" minOccurs="1">
			</element>
			<element name="join" type="tns:JoinType"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
		<attribute name="tableName" type="string"></attribute>
	</complexType>

	<complexType name="JoinType">
		<sequence>
			<element name="Field" type="tns:FieldType"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
		<attribute name="tableName" type="string"></attribute>
		<attribute name="name" type="string"></attribute>
	</complexType>

	<complexType name="FieldType">
    	<attribute name="sqlName" type="string"></attribute>
    	<attribute name="sqlNameRef" type="string"></attribute>
    	<attribute name="property" type="string"></attribute>
    	<attribute name="type" type="int"></attribute>
    	<attribute name="typeRef" type="int"></attribute>
    	<attribute name="key" type="boolean"></attribute>
    	<attribute name="joinRef" type="string"></attribute>
    </complexType>

</schema>

=== DLab/FONDEF-PID/GeneradorRAD/data/TipoArchivo.xml
<?xml version="1.0" encoding="UTF-8"?>
<Entity xmlns="http://www.example.org/Entity" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.example.org/Entity Entity.xsd "
	tableName="tipoarchivo">

  <field property="codigo"            	sqlName="tar_codigo"         	   	type="String"  key="true" />
  <field property="descripcion"   		sqlName="tar_descripcion"    		type="String"/>
  <field property="observaciones"   	sqlName="tar_observaciones"    		type="String"/>
  <field property="fechaCreacion"   	sqlName="tar_fec_creacion"    		type="Timestamp"/>
  <field property="ultModificacion"   	sqlName="tar_fec_ultmodificacion"   type="Timestamp"/>
  <field property="usuario"   			sqlName="tar_usr_id"    			type="String"/>
  <field property="codigoBaseDatos"   	sqlName="tar_bdt_codigo"    		type="String"/>
  
</Entity>

=== DLab/FONDEF-PID/GeneradorRAD/data/Usuario.xml
<?xml version="1.0" encoding="UTF-8"?>
<Entity xmlns="http://www.example.org/Entity" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.example.org/Entity Entity.xsd "
	tableName="usuario">

  <field property="id"           sqlName="usr_id"         	type="String"  key="true" />
  <field property="password"     sqlName="usr_password"    	type="Bytes"/>
  <field property="nombre"       sqlName="usr_nombre"    	type="String"/>
  <field property="idRol"        sqlName="usr_rol_id"       type="Integer"/>
  
  <field property="rol"           sqlNameRef="rol_descripcion"    type="Join" typeRef="String" joinRef="join1"/>
  
  <join name="join1" tableName="rol">
      <field sqlName="usr_rol_id" sqlNameRef="rol_id" />
  </join>
  
  <query id="unitary">
  	<field property="id"/>
  </query>
  
</Entity>
